name: Format Haskell Code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The GITHUB_TOKEN is required for the git push step.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2.8' # Or a version that suits your project
          cabal-version: '3.8'   # Or a version that suits your project

      - name: Install fourmolu
        run: cabal install fourmolu

      - name: Format code
        run: fourmolu --mode inplace $(find . -name "*.hs")

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "style: format code with fourmolu"
            git push
          else
            echo "No changes to commit."
          fi

